<?php
/* FAQ par défaut (repli si la table `faq` est vide + import admin). */
return [
  ["Qui peut s’inscrire aux formations IBIG EDUFORM ?", "Les formations sont ouvertes aux étudiants, professionnels, entrepreneurs, agents d’entreprise et toute personne souhaitant renforcer ses compétences. Chaque formation précise son public cible."],
  ["Les formations sont-elles certifiantes ?", "Oui. La majorité des formations IBIG EDUFORM donnent lieu à une attestation ou un certificat selon le programme suivi."],
  ["Les formations sont-elles en ligne ou en présentiel ?", "Les formations peuvent être dispensées en présentiel, en ligne ou en mode hybride selon les sessions."],
  ["Comment s’inscrire à une formation ?", "L’inscription se fait via le formulaire de préinscription disponible sur le site, suivi de la validation et du paiement."],
  ["La préinscription garantit-elle une place ?", "Non. La préinscription permet de manifester votre intérêt. La place est confirmée après validation et paiement."],
  ["Quels sont les moyens de paiement acceptés ?", "Les paiements peuvent être effectués par mobile money, virement bancaire, espèces ou tout autre moyen communiqué."],
  ["Les paiements peuvent-ils être échelonnés ?", "Certaines formations autorisent un paiement échelonné selon des modalités définies à l’avance."],
  ["Les frais de formation sont-ils remboursables ?", "En principe, les frais de formation ne sont pas remboursables. Des situations exceptionnelles peuvent être examinées sur demande écrite."],
  ["Puis-je changer de session après inscription ?", "Un report de session peut être envisagé sous réserve de disponibilité et validation par IBIG EDUFORM."],
  ["Que se passe-t-il en cas d’absence ?", "L’absence du participant n’ouvre pas droit à remboursement. Les contenus peuvent toutefois être partagés selon les règles internes."],
  ["Les supports de formation sont-ils fournis ?", "Oui. Les supports pédagogiques sont remis aux participants selon les modalités de la formation."],
  ["Puis-je partager les supports reçus ?", "Non. Les supports sont strictement personnels et protégés par le droit de la propriété intellectuelle."],
  ["Les formations garantissent-elles un emploi ?", "Non. IBIG EDUFORM ne garantit pas un emploi mais vise l’employabilité et la montée en compétences."],
  ["Proposez-vous des formations sur mesure ?", "Oui. IBIG EDUFORM conçoit des formations sur mesure pour les entreprises et organisations."],
  ["Les entreprises peuvent-elles inscrire plusieurs salariés ?", "Oui. Des dispositifs spécifiques sont proposés pour les entreprises."],
  ["Les formations sont-elles reconnues ?", "Les formations sont reconnues dans le cadre professionnel et orientées pratiques terrain."],
  ["Puis-je devenir formateur chez IBIG EDUFORM ?", "Oui. Vous pouvez soumettre votre candidature via la page Devenir formateur."],
  ["Comment contacter IBIG EDUFORM ?", "Les coordonnées de contact sont disponibles sur la page Contact du site."],
  ["Les formations sont-elles accessibles à l’international ?", "Oui. Les formations en ligne sont accessibles aux participants résidant hors de Côte d’Ivoire."],
  ["Proposez-vous des réductions ?", "Des réductions ponctuelles ou offres spéciales peuvent être proposées selon les sessions."],
  ["Comment sont protégées mes données personnelles ?", "Les données sont traitées conformément à la politique de confidentialité publiée sur le site."],
  ["Puis-je recevoir des informations par email ?", "Oui, sous réserve de votre consentement lors de l’inscription."],
  ["Puis-je annuler mon inscription ?", "Toute annulation est soumise aux conditions prévues dans les CGV et la politique de non-remboursement."],
  ["Les certificats sont-ils numériques ou physiques ?", "Les certificats peuvent être délivrés sous format numérique ou physique selon la formation."],
  ["Où trouver le calendrier des formations ?", "Le calendrier est disponible sur la page Calendrier des sessions du site IBIG EDUFORM."],
];
