<?php
declare(strict_types=1);
require_once __DIR__ . '/_init.php';
Middleware::requireAuth();
$pdo = Database::connect();
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$confirm = $_GET['confirm'] ?? '';

$formations = [

/* ═══════════════════════════════════════════════════════════
   1. SANTÉ & GESTION HOSPITALIÈRE
═══════════════════════════════════════════════════════════ */
['slug'=>'gestion-etablissement-sante-ci','titre'=>'Gestion d\'un établissement de santé en Côte d\'Ivoire','domaine'=>'Santé & Gestion hospitalière','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur la gestion administrative, financière et réglementaire d'une clinique, polyclinique ou centre médical en Côte d'Ivoire. Couvre l'organisation interne, le cadre légal du Ministère de la Santé, la tarification des actes, la gestion du personnel soignant et la relation avec les assurances maladie. Référence : IBIG-SAN-GES.",
'objectifs'=>"Comprendre le cadre réglementaire des établissements de santé privés en Côte d'Ivoire\nOrganiser les services médicaux et paramédicaux d'un établissement\nMettre en place un système de tarification et de facturation des actes\nGérer les relations avec la CNAM-CI et les mutuelles\nPiloter les ressources humaines soignantes (recrutement, planning, formation)\nContrôler les coûts et optimiser la rentabilité\nMettre en place un système qualité et de gestion des plaintes patients\nPréparer une accréditation ou une inspection du Ministère de la Santé",
'modules'=>"M1 — Cadre légal et agrément (3h) : réglementation des cliniques privées, Ministère de la Santé, conditions d'ouverture et de renouvellement\nM2 — Organisation et gouvernance (3h) : organigramme, fonctions médicales/paramédicales/administratives, règlement intérieur\nM3 — Finances et facturation (4h) : tarification des actes, facturation CNAM-CI et mutuelles, gestion des impayés, trésorerie\nM4 — Ressources humaines (4h) : statut du personnel soignant, planning, évaluation, formation continue obligatoire\nM5 — Achats et stocks médicaux (3h) : gestion de la pharmacie interne, consommables, matériel médical\nM6 — Qualité et sécurité des soins (4h) : indicateurs qualité, hygiène hospitalière, gestion des incidents et des plaintes\nM7 — Pilotage et tableau de bord (4h) : indicateurs clés, rapport d'activité, plan de développement"],

['slug'=>'facturation-medicale-assurance-cnam','titre'=>'Facturation médicale et assurance maladie CNAM-CI','domaine'=>'Santé & Gestion hospitalière','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation pratique de 20 heures sur la facturation médicale et les procédures de remboursement de la CNAM-CI (Couverture Maladie Universelle). Destinée aux gestionnaires de cliniques, agents de facturation et comptables d'établissements de santé. Couvre la nomenclature des actes, la tarification, le tiers payant et le recouvrement des créances sur les assureurs. Référence : IBIG-SAN-FACT.",
'objectifs'=>"Maîtriser la nomenclature générale des actes professionnels (NGAP) applicable en Côte d'Ivoire\nÉtablir des feuilles de soins et des factures conformes aux exigences de la CNAM-CI\nAppliquer les procédures de tiers payant et d'avance de frais\nGérer les rejets et les litiges de remboursement\nSuivre les créances sur les organismes payeurs\nConnaître les obligations légales de l'établissement envers l'assurance maladie\nUtiliser les outils de télétransmission des feuilles de soins",
'modules'=>"M1 — Système d'assurance maladie en CI (2h) : CMU, CNAM-CI, mutuelles, organismes complémentaires, droits des patients\nM2 — Nomenclature et codification des actes (4h) : NGAP, codes actes, tarifs opposables, consultations et hospitalisations\nM3 — Établissement des factures médicales (4h) : ordonnances, feuilles de soins, bulletin de situation, bon de prise en charge\nM4 — Tiers payant et télétransmission (3h) : procédure CMU, avance de frais, logiciels de facturation\nM5 — Rejets et litiges (4h) : causes de rejet fréquentes, contestation, suivi des remboursements, relances\nM6 — Cas pratiques et évaluation (3h) : mise en situation, correction, certification"],

['slug'=>'gestion-stocks-pharmacie-hopital','titre'=>'Gestion des stocks en pharmacie hospitalière','domaine'=>'Santé & Gestion hospitalière','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur la gestion des stocks de médicaments, consommables médicaux et équipements dans les officines et pharmacies hospitalières. Couvre les bonnes pratiques de stockage, la gestion des périmés, les procédures de commande, les outils informatiques de gestion et la réglementation pharmaceutique en Côte d'Ivoire. Référence : IBIG-SAN-PHR.",
'objectifs'=>"Appliquer les règles de stockage et de conservation des médicaments\nMettre en place un système de gestion des entrées et sorties (FIFO, FEFO)\nPlanifier les commandes et éviter les ruptures de stock\nGérer les médicaments à prescription restreinte et les stupéfiants\nSuivre les dates de péremption et gérer les produits périmés\nUtiliser un logiciel de gestion de pharmacie\nRéaliser un inventaire physique conforme aux bonnes pratiques",
'modules'=>"M1 — Réglementation pharmaceutique CI (2h) : lois, Ordre des Pharmaciens, inspection, autorisation d'exercice\nM2 — Classification et conservation des médicaments (3h) : chaîne du froid, conditions de stockage, produits réglementés\nM3 — Gestion des entrées/sorties (4h) : réception, bon de livraison, FIFO/FEFO, traçabilité\nM4 — Planification des commandes (4h) : stock minimum, délai fournisseur, commande optimale, budget\nM5 — Gestion des périmés et des retours (3h) : identification, procédure de destruction, responsabilité légale\nM6 — Outils et évaluation (4h) : logiciels (PHARMAcie, Excel), inventaire, indicateurs, cas pratiques"],

['slug'=>'management-equipes-soignantes','titre'=>'Management des équipes soignantes et qualité des soins','domaine'=>'Santé & Gestion hospitalière','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures dédiée aux cadres de santé, infirmiers chefs et directeurs d'établissements. Couvre le management des équipes pluridisciplinaires, la planification des gardes et des soins, la gestion des conflits en milieu médical et la démarche qualité des soins. Référence : IBIG-SAN-MAN.",
'objectifs'=>"Adapter son style de management aux spécificités du secteur de la santé\nPlanifier les plannings de soins et les gardes dans le respect de la réglementation\nMotiver et fidéliser le personnel soignant dans un contexte de pénurie\nGérer les conflits interprofessionnels et les situations de crise\nMettre en œuvre une démarche qualité et de sécurité des soins\nÉvaluer les compétences et accompagner la montée en compétences\nProduire les indicateurs de qualité et les rapports d'activité de service",
'modules'=>"M1 — Spécificités du management en santé (3h) : hiérarchie médicale vs administrative, autorité, responsabilités\nM2 — Organisation et planification des soins (4h) : planning, gardes, protocoles de soins, continuité des soins\nM3 — Motivation et fidélisation (4h) : leviers de motivation en milieu soignant, reconnaissance, formation continue\nM4 — Gestion des conflits (3h) : sources de tension fréquentes, médiation, communication non violente\nM5 — Démarche qualité des soins (5h) : indicateurs qualité, audits internes, signalement des événements indésirables, accréditation\nM6 — Évaluation des compétences (3h) : entretien annuel, grilles d'évaluation, plan de formation\nM7 — Cas de synthèse (3h) : simulation de situation managériale complexe"],

['slug'=>'hygiene-hospitaliere-prevention-infections','titre'=>'Hygiène hospitalière et prévention des infections nosocomiales','domaine'=>'Santé & Gestion hospitalière','duree'=>'15H','tarif_en_ligne'=>170000,'tarif_presentiel'=>215000,
'description'=>"Formation de 15 heures sur l'hygiène en établissement de santé et la prévention des infections associées aux soins (IAS). Destinée aux infirmiers, aides-soignants, agents d'entretien et responsables qualité d'hôpitaux et cliniques. Couvre les précautions standard, la stérilisation, le bionettoyage et la gestion des déchets médicaux. Référence : IBIG-SAN-HYG.",
'objectifs'=>"Appliquer les précautions standard de prévention des infections\nMaîtriser les techniques de lavage des mains et d'hygiène des mains\nOrganiser la stérilisation du matériel médical et le bionettoyage des locaux\nGérer les déchets d'activités de soins à risques infectieux (DASRI)\nSurveiller les infections nosocomiales et mettre en place des mesures correctives\nFormer le personnel aux bonnes pratiques d'hygiène",
'modules'=>"M1 — Infections nosocomiales et IAS (2h30) : définitions, épidémiologie, conséquences, responsabilité\nM2 — Précautions standard (3h) : hygiène des mains, équipements de protection individuelle, précautions complémentaires\nM3 — Stérilisation et bionettoyage (3h) : procédures de stérilisation, niveaux de désinfection, bionettoyage des surfaces\nM4 — Gestion des DASRI (3h) : tri, conditionnement, stockage, transport et élimination des déchets médicaux\nM5 — Surveillance et amélioration continue (3h30) : indicateurs, audits hygiène, retour d'expérience, formation du personnel"],

/* ═══════════════════════════════════════════════════════════
   2. ÉDUCATION & FORMATION PROFESSIONNELLE
═══════════════════════════════════════════════════════════ */
['slug'=>'ingenierie-pedagogique-conception-formation','titre'=>'Ingénierie pédagogique et conception de formations','domaine'=>'Éducation & Formation','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur l'ingénierie pédagogique appliquée à la conception de programmes de formation professionnelle. Destinée aux responsables formation, formateurs et chefs de projet pédagogique. Couvre l'analyse des besoins, la rédaction de cahiers des charges, la création de supports et l'évaluation des apprentissages. Référence : IBIG-EDU-ING.",
'objectifs'=>"Réaliser une analyse des besoins en formation (ABF) rigoureuse\nRédiger un cahier des charges pédagogique et un plan de formation\nConcevoir un curriculum de formation structuré et cohérent\nChoisir les méthodes et modalités pédagogiques adaptées aux objectifs\nCréer des supports pédagogiques efficaces (diapositives, fiches, e-learning)\nÉvaluer les apprentissages à chaud et à froid\nPiloter un projet de formation de A à Z",
'modules'=>"M1 — Fondamentaux de la pédagogie pour adultes (3h) : andragogie, styles d'apprentissage, motivation\nM2 — Analyse des besoins en formation (4h) : interview, questionnaire, analyse des écarts de compétences, ABF\nM3 — Conception du curriculum (4h) : objectifs pédagogiques SMART, séquencement, durée, prérequis\nM4 — Méthodes et modalités (3h) : exposé, cas pratique, simulation, e-learning, blended learning\nM5 — Création de supports (5h) : diapositives structurées, fiches participant, activités, quiz\nM6 — Évaluation des apprentissages (3h) : évaluation formative et sommative, grilles, certification\nM7 — Gestion de projet pédagogique (3h) : planning, budget, coordination des intervenants, bilan"],

['slug'=>'gestion-ecole-privee-ci','titre'=>'Gestion administrative et financière d\'une école privée en Côte d\'Ivoire','domaine'=>'Éducation & Formation','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur la création et la gestion d'un établissement d'enseignement privé en Côte d'Ivoire : maternelle, primaire, secondaire ou centre de formation professionnelle. Couvre le cadre légal (MENET-FP, METFP), l'agrément, la gestion financière, le personnel enseignant et la relation avec les familles. Référence : IBIG-EDU-GES.",
'objectifs'=>"Connaître le cadre légal et les conditions d'ouverture d'une école privée en Côte d'Ivoire\nConstituer un dossier d'agrément auprès du Ministère de l'Éducation\nOrganiser les structures pédagogique et administrative de l'établissement\nGérer les inscriptions, les scolarités et les paiements\nPiloter les ressources humaines enseignantes et non enseignantes\nÉtablir un budget prévisionnel et suivre la trésorerie de l'école\nGérer la relation avec les parents d'élèves et le conseil d'établissement",
'modules'=>"M1 — Cadre légal (2h30) : loi sur l'enseignement privé, agrément, inspection, obligations de l'établissement\nM2 — Dossier d'ouverture et agrément (2h30) : pièces requises, démarches MENET-FP/METFP, autorisations\nM3 — Organisation pédagogique (3h) : programmes officiels, emplois du temps, calendrier scolaire, conseils de classe\nM4 — Administration et inscriptions (3h) : dossiers élèves, scolarités, logiciels de gestion scolaire\nM5 — RH enseignants (3h) : recrutement, statut, contrats, CAFOP, évaluation pédagogique\nM6 — Gestion financière (4h) : budget, trésorerie, scolarités impayées, comptabilité de l'école\nM7 — Communication et qualité (2h) : relation parents, site web, réputation, amélioration continue"],

['slug'=>'devenir-formateur-professionnel','titre'=>'Devenir formateur professionnel certifié','domaine'=>'Éducation & Formation','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures pour acquérir les compétences clés du formateur professionnel d'adultes : animation, posture pédagogique, gestion de groupe et évaluation. Inclut des mises en situation filmées et un coaching individuel. À l'issue : certificat de formateur professionnel IBIG EDUFORM. Référence : IBIG-EDU-FRM.",
'objectifs'=>"Adopter la posture et l'éthique du formateur professionnel\nPréparer et structurer une séance de formation\nAnimer une formation en présentiel et à distance\nGérer la dynamique de groupe et les apprenants difficiles\nUtiliser les techniques d'animation actives et participatives\nÉvaluer les apprentissages en cours et en fin de formation\nConstruire son identité de formateur et développer son activité",
'modules'=>"M1 — Identité et posture du formateur (2h) : rôles, responsabilités, éthique, positionnement\nM2 — Préparation d'une formation (3h) : fiche de préparation, timing, matériel, environnement\nM3 — Techniques d'animation (5h) : exposé interactif, brainstorming, jeux de rôle, études de cas, démonstration\nM4 — Gestion du groupe (3h) : dynamique de groupe, apprenants difficiles, gestion du temps, énergie du groupe\nM5 — Animation en distanciel (3h) : outils (Zoom, Teams, Moodle), engagement à distance, breakout rooms\nM6 — Évaluation et certification (4h) : évaluation formative, QCM, mises en situation, certification"],

['slug'=>'conception-formation-ligne-elearning','titre'=>'Concevoir et animer une formation en ligne (e-learning)','domaine'=>'Éducation & Formation','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur la conception et l'animation de formations digitales : cours asynchrones, webinaires, MOOC et blended learning. Couvre les outils auteurs (Genially, Canva, PowerPoint avancé), les LMS (Moodle, Google Classroom), le tournage de vidéos pédagogiques et l'engagement des apprenants à distance. Référence : IBIG-EDU-ELN.",
'objectifs'=>"Concevoir un cours en ligne structuré et engageant\nChoisir et utiliser un LMS adapté à son contexte (Moodle, Google Classroom, Teachable)\nCréer des contenus multimédias : vidéos, quiz interactifs, infographies\nAnimer des webinaires et des classes virtuelles dynamiques\nGérer une communauté d'apprenants en ligne\nÉvaluer et certifier les apprenants à distance\nMonétiser une formation en ligne",
'modules'=>"M1 — Design pédagogique pour le digital (2h30) : scénarisation, micro-learning, engagement\nM2 — Outils de création de contenu (4h) : Genially, Canva, PowerPoint animé, H5P, quiz\nM3 — Production vidéo pédagogique (3h30) : tournage smartphone, montage (CapCut, Clipping), sous-titrage\nM4 — LMS et plateformes (3h) : Moodle, Google Classroom, Teachable : mise en ligne et paramétrage\nM5 — Animation de webinaires (3h) : Zoom, Teams, breakout rooms, sondages, tableau blanc\nM6 — Évaluation à distance et certification (3h) : quiz automatisés, badges, attestations numériques\nM7 — Monétisation et marketing (1h) : tarification, plateformes de vente, promotion"],

['slug'=>'evaluation-competences-certification','titre'=>'Évaluation des apprentissages et certification des compétences','domaine'=>'Éducation & Formation','duree'=>'15H','tarif_en_ligne'=>170000,'tarif_presentiel'=>215000,
'description'=>"Formation de 15 heures sur la conception et la mise en œuvre de dispositifs d'évaluation des compétences professionnelles. Destinée aux responsables formation, RH et formateurs. Couvre les référentiels de compétences, les outils d'évaluation, la validation des acquis et les processus de certification. Référence : IBIG-EDU-EVA.",
'objectifs'=>"Distinguer évaluation formative, sommative et certificative\nConstruire un référentiel de compétences métier\nConcevoir des outils d'évaluation valides et fiables\nConducter des épreuves de certification en présentiel et à distance\nValider les acquis de l'expérience (VAE)\nMettre en place un portefeuille de compétences\nReconnaître et valoriser les certifications professionnelles dans l'entreprise",
'modules'=>"M1 — Fondamentaux de l'évaluation (2h30) : formes d'évaluation, validité, fiabilité, équité\nM2 — Référentiels de compétences (3h) : construction d'un référentiel métier, niveaux de maîtrise, taxonomie de Bloom\nM3 — Outils d'évaluation (3h) : QCM, étude de cas, mise en situation, grille d'observation, portfolio\nM4 — Certification et VAE (3h30) : processus de certification, jury, VAE, reconnaissance des acquis\nM5 — Évaluation numérique (3h) : quiz en ligne, badges numériques, micro-credentials, OpenBadges"],

/* ═══════════════════════════════════════════════════════════
   3. BTP & GESTION DE CHANTIER
═══════════════════════════════════════════════════════════ */
['slug'=>'gestion-projet-btp-conducteur-travaux','titre'=>'Gestion de projet BTP et conduite de chantier','domaine'=>'BTP & Génie civil','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur la gestion opérationnelle d'un chantier de construction : planification, pilotage des équipes, suivi budgétaire, coordination des corps de métier et réception des travaux. Applicable aux projets résidentiels, commerciaux et industriels en Côte d'Ivoire et dans la sous-région. Référence : IBIG-BTP-CDT.",
'objectifs'=>"Lire et interpréter les plans architecturaux et les CCTP\nPlanifier un chantier avec un planning de type Gantt et chemin critique\nOrganiser et coordonner les corps de métier sur le chantier\nSuivre l'avancement physique et financier des travaux\nGérer les approvisionnements et éviter les ruptures de matériaux\nIdentifier et gérer les risques techniques et sécuritaires\nRédiger les rapports de chantier et préparer la réception des travaux",
'modules'=>"M1 — Lecture de plans et CCTP (3h) : plans architecturaux, plans d'exécution, cahiers des charges techniques\nM2 — Planification du chantier (4h) : décomposition en lots, planning Gantt, chemin critique, suivi d'avancement\nM3 — Organisation des équipes (3h) : sous-traitants, intérimaires, coordination interentreprises, PPSPS\nM4 — Suivi budgétaire (4h) : budget prévisionnel, attachements, situations de travaux, écarts et révisions\nM5 — Approvisionnements (3h) : commandes matériaux, délais, réception et contrôle qualité des livraisons\nM6 — Sécurité sur chantier (4h) : EPI, consignation, risques électriques et de chute, accidents et déclaration\nM7 — Réception et clôture (4h) : levée des réserves, procès-verbal de réception, DOE, garanties"],

['slug'=>'metres-devis-estimation-construction','titre'=>'Métrés, devis et estimation des coûts de construction','domaine'=>'BTP & Génie civil','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation pratique de 20 heures sur le métré des ouvrages de bâtiment et la rédaction de devis quantitatifs et estimatifs. Apprendre à chiffrer un projet de construction de A à Z : gros œuvre, second œuvre, finitions, VRD. Nombreux exercices sur plans réels. Référence : IBIG-BTP-MET.",
'objectifs'=>"Effectuer le métré d'ouvrages de bâtiment à partir de plans\nRédiger un avant-métré et un devis quantitatif détaillé\nEstimer les coûts unitaires des matériaux et de la main-d'œuvre en Côte d'Ivoire\nÉtablir un devis estimatif global d'un projet de construction\nComparer des offres de sous-traitants et négocier les prix\nUtiliser Excel pour automatiser les calculs de métrés\nComprendre les écarts entre devis et exécution",
'modules'=>"M1 — Introduction au métré (2h) : définitions, types de devis, documents contractuels, CCTP\nM2 — Métrés de gros œuvre (5h) : terrassements, fondations, maçonnerie, béton armé, charpente\nM3 — Métrés de second œuvre (4h) : plomberie, électricité, menuiseries, revêtements, peintures\nM4 — Prix unitaires et sous-détails (4h) : coûts matériaux en CI, main-d'œuvre, outillage, marge\nM5 — Rédaction du devis estimatif (3h) : structuration, présentation, bordereau de prix, récapitulatif\nM6 — Exercices sur plans réels (2h) : application complète sur un projet résidentiel"],

['slug'=>'securite-prevention-chantier-btp','titre'=>'Sécurité et prévention des risques sur chantier','domaine'=>'BTP & Génie civil','duree'=>'15H','tarif_en_ligne'=>170000,'tarif_presentiel'=>215000,
'description'=>"Formation de 15 heures sur la sécurité au travail dans le secteur du BTP. Destinée aux conducteurs de travaux, chefs de chantier et maîtres d'ouvrage. Couvre la réglementation ivoirienne (Code du travail, inspection du travail), les risques spécifiques du bâtiment, les équipements de protection et la rédaction du PPSPS. Référence : IBIG-BTP-SEC.",
'objectifs'=>"Identifier les risques spécifiques aux chantiers de construction\nConnaître la réglementation sécurité applicable au BTP en Côte d'Ivoire\nRédiger un plan particulier de sécurité et de protection de la santé (PPSPS)\nChoisir et faire utiliser les équipements de protection individuelle\nOrganiser les secours et gérer les accidents du travail\nMettre en place les protections collectives obligatoires\nFormer les compagnons aux gestes et postures de sécurité",
'modules'=>"M1 — Cadre légal BTP en Côte d'Ivoire (2h) : Code du travail, inspection, obligations employeur, déclaration accidents\nM2 — Identification des risques (3h) : chutes de hauteur, risques électriques, engins, produits chimiques, co-activité\nM3 — PPSPS et plan de prévention (3h) : rédaction, contenu obligatoire, coordination SPS\nM4 — EPI et protections collectives (3h) : choix, port, entretien des équipements, garde-corps, filets\nM5 — Secours et gestion des accidents (2h) : premiers secours, déclaration AT, CNPS, enquête accidents\nM6 — Sensibilisation et formation des équipes (2h) : causeries sécurité, affichage, habilitations"],

['slug'=>'urbanisme-permis-construire-ci','titre'=>'Urbanisme, permis de construire et réglementation en Côte d\'Ivoire','domaine'=>'BTP & Génie civil','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur le droit de l'urbanisme et les procédures d'obtention du permis de construire en Côte d'Ivoire. Destinée aux promoteurs, architectes, entrepreneurs BTP et propriétaires fonciers. Couvre le Code de l'urbanisme, les documents d'urbanisme (PUD, lotissements), les servitudes et le contentieux de l'urbanisme. Référence : IBIG-BTP-URB.",
'objectifs'=>"Comprendre le cadre légal de l'urbanisme en Côte d'Ivoire\nLire et interpréter un plan d'urbanisme directeur (PUD)\nConstituer et déposer un dossier de permis de construire\nConnaître les servitudes d'utilité publique et les règles de prospect\nÉviter les constructions illicites et leurs conséquences\nSuivre l'instruction d'un permis et gérer les recours\nComprendre le régime des lotissements et des morcellements",
'modules'=>"M1 — Droit de l'urbanisme en CI (3h) : cadre légal, Ministère de la Construction, DUA, communes\nM2 — Documents d'urbanisme (3h) : PUD, SDAU, POS, lotissements, zones constructibles\nM3 — Permis de construire (5h) : pièces du dossier, dépôt, instruction, délais, permis tacite\nM4 — Servitudes et règles de construction (3h) : prospects, hauteurs, implantation, réseaux\nM5 — Constructions illicites et contentieux (3h) : risques, démolition, régularisation, recours gracieux\nM6 — Lotissements et morcellements (3h) : procédure, viabilisation, charges foncières"],

['slug'=>'gestion-approvisionnement-materiaux-btp','titre'=>'Gestion des approvisionnements et des matériaux en BTP','domaine'=>'BTP & Génie civil','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur la gestion des achats, des stocks et des approvisionnements en matériaux de construction. Couvre la planification des besoins, la sélection des fournisseurs, la réception des livraisons, la gestion du stock de chantier et la lutte contre les gaspillages et vols de matériaux. Référence : IBIG-BTP-APP.",
'objectifs'=>"Planifier les besoins en matériaux à partir du planning de chantier\nSélectionner et évaluer les fournisseurs de matériaux en Côte d'Ivoire\nNégocier les prix et les délais de livraison\nRéceptionner et contrôler la conformité des livraisons\nGérer le stock de matériaux sur chantier et éviter les ruptures\nLutter contre les gaspillages et les vols de matériaux\nMettre en place un tableau de bord des approvisionnements",
'modules'=>"M1 — Planification des besoins (3h) : quantitatif matériaux, calendrier des commandes, budget\nM2 — Sélection des fournisseurs (3h) : critères de sélection, consultation, évaluation des offres\nM3 — Négociation achat (3h) : techniques de négociation, contrat d'achat, conditions de paiement\nM4 — Réception et contrôle qualité (4h) : bon de livraison, contrôle conformité, non-conformités\nM5 — Gestion du stock chantier (4h) : organisation du dépôt, inventaire, sécurisation\nM6 — Tableau de bord et reporting (3h) : indicateurs, écarts budget/réel, rapport au maître d'ouvrage"],

/* ═══════════════════════════════════════════════════════════
   4. AGRICULTURE & AGROALIMENTAIRE
═══════════════════════════════════════════════════════════ */
['slug'=>'transformation-agroalimentaire-haccp-afrique','titre'=>'Transformation agroalimentaire et normes HACCP en Afrique','domaine'=>'Agriculture & Agroalimentaire','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur la transformation des produits agricoles et l'application des normes d'hygiène et de sécurité alimentaire (HACCP) dans le contexte africain. Couvre les filières cacao, anacarde, manioc, fruits tropicaux, lait et produits carnés. Destinée aux entrepreneurs agroalimentaires, responsables qualité et agents de contrôle. Référence : IBIG-AGR-HACP.",
'objectifs'=>"Maîtriser les principes HACCP et leur application en agroalimentaire africain\nIdentifier les dangers biologiques, chimiques et physiques dans les filières locales\nConcevoir et implémenter un plan HACCP adapté à une PME agroalimentaire\nApplliquer les bonnes pratiques d'hygiène (BPH) et de fabrication (BPF)\nComprendre les exigences de la norme ISO 22000 et du Codex Alimentarius\nMaîtriser les procédures de contrôle qualité et de traçabilité\nPréparer un dossier d'homologation auprès du LANEMA/ANADER en Côte d'Ivoire",
'modules'=>"M1 — Sécurité alimentaire et cadre réglementaire (3h) : Codex Alimentarius, réglementation ivoirienne, LANEMA\nM2 — Principes HACCP (5h) : 7 principes, diagramme de flux, points critiques (CCP), limites critiques\nM3 — BPH et BPF (4h) : hygiène du personnel, des locaux, des équipements, nettoyage-désinfection\nM4 — Filières agroalimentaires ivoiriennes (4h) : cacao, anacarde, manioc, fruits — dangers et maîtrise spécifique\nM5 — Traçabilité et gestion des non-conformités (4h) : étiquetage, codes-barres, gestion des rappels produits\nM6 — ISO 22000 et audit (5h) : structure de la norme, plan de surveillance, préparation à un audit de certification"],

['slug'=>'business-modele-financement-agricole-ci','titre'=>'Business model agricole et financement en Côte d\'Ivoire','domaine'=>'Agriculture & Agroalimentaire','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures pour les entrepreneurs agricoles qui souhaitent structurer leur activité et accéder aux financements disponibles en Côte d'Ivoire : FIRCA, FIDA, banques agricoles, fonds de garantie, warrantage. Couvre la rédaction d'un business plan agricole et la présentation aux financeurs. Référence : IBIG-AGR-FIN.",
'objectifs'=>"Définir un modèle économique agricole viable et rentable\nRédiger un business plan agricole adapté aux exigences des financeurs\nConnaître les mécanismes de financement agricole disponibles en CI\nConstituer et déposer un dossier de financement auprès d'une banque ou du FIRCA\nComprendre le warrantage et les autres mécanismes de garantie\nGérer la trésorerie saisonnière d'une exploitation agricole\nNégocier avec les acheteurs (coopératives, exportateurs, transformateurs)",
'modules'=>"M1 — Modèle économique agricole (3h) : Business Model Canvas adapté à l'agriculture, types d'exploitation\nM2 — Business plan agricole (5h) : étude de marché, prévisionnel de production et financier, risques\nM3 — Mécanismes de financement (4h) : FIRCA, BCEAO-ADFI, banques (SIB, SGCI, BICICI), microfinance, FIDA\nM4 — Warrantage et garanties (3h) : principe, conditions, procédure, avantages pour l'exploitant\nM5 — Gestion de la trésorerie agricole (3h) : saisonnalité, couverture des charges, plan de trésorerie\nM6 — Négociation et contrats avec acheteurs (2h) : contrats de culture, prix de référence, coopératives"],

['slug'=>'export-produits-agricoles-cedeao','titre'=>'Exportation de produits agricoles dans la CEDEAO','domaine'=>'Agriculture & Agroalimentaire','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur les procédures d'exportation des produits agricoles et agroalimentaires ivoiriens vers les marchés régionaux (CEDEAO) et internationaux (UE, USA). Couvre les normes phytosanitaires, le conditionnement, les certifications d'origine, la logistique et les incoterms. Référence : IBIG-AGR-EXP.",
'objectifs'=>"Identifier les marchés porteurs pour les produits agricoles ivoiriens\nConnaître les normes phytosanitaires et sanitaires à l'exportation\nConstituer un dossier d'exportation complet\nChoisir les Incoterms adaptés et sécuriser les paiements internationaux\nGérer le conditionnement et l'emballage pour l'export\nObtenir les certifications nécessaires (Global G.A.P, Fairtrade, Bio)\nUtiliser les accords commerciaux CEDEAO et APE pour l'exportation",
'modules'=>"M1 — Marchés et opportunités d'export (2h) : CEDEAO, UE, Asie — produits porteurs, volumes, prix\nM2 — Cadre réglementaire export (3h) : OCPV, CNPS, Douanes, normes phytosanitaires, TRACES\nM3 — Dossier d'exportation (3h) : certificat d'origine, phytosanitaire, certificat de conformité, documents douaniers\nM4 — Conditionnement et logistique (4h) : emballage export, conteneurs, transport maritime/aérien, Incoterms\nM5 — Paiement et financement de l'export (3h) : crédit documentaire, remise documentaire, assurance-crédit\nM6 — Certifications et labels (3h) : Bio, Fairtrade, Global G.A.P, Rainforest Alliance — procédures\nM7 — Mise en pratique (2h) : simulation d'un dossier export complet"],

['slug'=>'gestion-exploitation-agricole-rentable','titre'=>'Gestion d\'une exploitation agricole rentable','domaine'=>'Agriculture & Agroalimentaire','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur la gestion opérationnelle, financière et commerciale d'une exploitation agricole. Couvre la planification des cultures, la gestion de la main-d'œuvre agricole, le suivi des coûts de production, la commercialisation et l'accès aux nouvelles technologies agricoles (agritech). Référence : IBIG-AGR-GES.",
'objectifs'=>"Planifier un calendrier cultural optimisé selon la saisonnalité\nGérer la main-d'œuvre agricole saisonnière et permanente\nCalculer les coûts de production et le seuil de rentabilité par culture\nMettere en place un suivi comptable simplifié pour l'exploitation\nCommercialiser la production au meilleur prix\nIntroduire des technologies agricoles accessibles (mobile, drone, irrigation)\nDiversifier les revenus de l'exploitation",
'modules'=>"M1 — Planification des cultures (4h) : assolement, rotation, itinéraire technique, calendrier cultural\nM2 — Gestion de la main-d'œuvre (3h) : contrats saisonniers, tâches, contrôle du travail, sécurité\nM3 — Coûts de production (4h) : inputs, amortissements, main-d'œuvre, coût unitaire, marge brute\nM4 — Comptabilité agricole simplifiée (4h) : journal de caisse, inventaire, bilan simplifié\nM5 — Commercialisation (4h) : marchés locaux, coopératives, contrats d'approvisionnement, prix de référence\nM6 — Agritech et innovations (3h) : applications mobiles agricoles, SMS météo, irrigation goutte-à-goutte\nM7 — Diversification (3h) : élevage associé, transformation à la ferme, écotourisme"],

['slug'=>'agro-transformation-packaging-commercialisation','titre'=>'Agro-transformation, packaging et commercialisation','domaine'=>'Agriculture & Agroalimentaire','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures pour les entrepreneurs qui souhaitent transformer des produits agricoles locaux (attiéké, jus de fruits, huile de palme, noix de cajou, etc.) en produits finis vendables sur les marchés local, régional et international. Couvre la transformation, le conditionnement, l'étiquetage, la distribution et les normes. Référence : IBIG-AGR-TRSF.",
'objectifs'=>"Maîtriser les procédés de transformation des principaux produits agricoles ivoiriens\nChoisir et mettre en place un atelier de transformation adapté\nConcevoir un packaging attractif et conforme aux normes\nRédiger un étiquetage conforme à la réglementation ivoirienne et CEDEAO\nDéfinir une stratégie de distribution (supermarchés, restauration, export)\nFixer les prix de vente avec une marge saine\nObtenir les autorisations sanitaires nécessaires",
'modules'=>"M1 — Procédés de transformation (4h) : séchage, broyage, pressage, pasteurisation, fermentation\nM2 — Équipements et atelier (3h) : choix du matériel, implantation, coûts d'investissement\nM3 — Packaging et étiquetage (4h) : matériaux d'emballage, conception du pack, DLC/DLUO, étiquetage réglementaire\nM4 — Autorisations et normes (3h) : agrément sanitaire LANEMA, DGCI, GS1 (codes-barres)\nM5 — Distribution et commercialisation (3h) : GMS, restauration collective, e-commerce, exportation\nM6 — Fixation des prix et marge (3h) : coûts de revient, prix de vente, point mort, politique tarifaire"],

/* ═══════════════════════════════════════════════════════════
   5. DOUANES & COMMERCE INTERNATIONAL
═══════════════════════════════════════════════════════════ */
['slug'=>'dedouanement-procedures-douanieres-ci','titre'=>'Dédouanement et procédures douanières en Côte d\'Ivoire','domaine'=>'Douanes & Commerce international','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur les procédures de dédouanement à l'import et à l'export en Côte d'Ivoire. Destinée aux transitaires, commissionnaires en douane, responsables logistique et importateurs/exportateurs. Couvre la réglementation douanière ivoirienne, le système SYDONIA, les régimes douaniers, le paiement des droits et taxes, et la gestion des litiges douaniers. Référence : IBIG-DOA-DED.",
'objectifs'=>"Comprendre le cadre réglementaire des douanes en Côte d'Ivoire\nMaîtriser les étapes du processus de dédouanement import et export\nUtiliser le système SYDONIA World pour la déclaration en douane\nDéterminer la valeur en douane et la classification tarifaire (SH)\nCalculer les droits et taxes dus à l'importation\nConnaître les régimes douaniers et choisir le régime adapté\nGérer un litige douanier et rédiger un recours",
'modules'=>"M1 — Organisation des douanes en CI (3h) : Direction Générale des Douanes, bureaux de douane, compétences, rôle\nM2 — Classification tarifaire (4h) : Système Harmonisé (SH), Tarif extérieur commun CEDEAO, position tarifaire\nM3 — Valeur en douane (3h) : méthodes de valorisation (méthode transactionnelle et méthodes subsidiaires)\nM4 — Droits et taxes à l'importation (4h) : DDI, RSTA, TVA, PRELVT, calcul pratique\nM5 — SYDONIA World (4h) : saisie d'une déclaration, pièces requises, paiement, mainlevée\nM6 — Régimes douaniers (4h) : mise à la consommation, transit, admission temporaire, entrepôt, perfectionnement\nM7 — Litiges et contentieux douanier (3h) : vérification, saisie, amende, recours, pénalités"],

['slug'=>'incoterms-transport-international','titre'=>'Incoterms, transport international et logistique documentaire','domaine'=>'Douanes & Commerce international','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur les Incoterms 2020, les modes de transport international et la gestion de la chaîne documentaire du commerce extérieur. Apprendre à choisir le bon Incoterm, à gérer les risques et assurances, et à traiter les documents du commerce international (connaissement, lettre de crédit, certificat d'origine). Référence : IBIG-DOA-INC.",
'objectifs'=>"Maîtriser les 11 Incoterms 2020 et leurs implications pour vendeur et acheteur\nChoisir l'Incoterm adapté à sa situation commerciale et logistique\nComprendre les modes de transport maritime, aérien, terrestre et multimodal\nGérer les risques de transport et souscrire une assurance marchandise adaptée\nTraiter les documents du commerce international : connaissement, B/L, LTA, AWB\nMonter et contrôler un dossier documentaire complet\nRégler les litiges de transport international",
'modules'=>"M1 — Fondamentaux des Incoterms 2020 (3h) : historique, rôle, structure, groupes E/F/C/D\nM2 — Les 11 Incoterms en détail (5h) : EXW, FCA, FAS, FOB, CFR, CIF, CPT, CIP, DAP, DPU, DDP\nM3 — Modes de transport (4h) : maritime, aérien, routier, ferroviaire, multimodal — chargeurs et affrètement\nM4 — Assurance marchandise (2h) : risques, polices d'assurance, clauses CGA, déclaration sinistre\nM5 — Documents du commerce international (4h) : connaissement (B/L), LTA, AWB, facture commerciale, liste de colisage, certificat d'origine\nM6 — Cas pratiques et litiges (2h) : simulation d'une opération import, gestion d'un litige de transport"],

['slug'=>'regimes-douaniers-cedeao-zones-franches','titre'=>'Régimes douaniers CEDEAO/UEMOA et zones franches','domaine'=>'Douanes & Commerce international','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur les régimes douaniers préférentiels de la CEDEAO et de l'UEMOA, les zones franches industrielles (ZFI) et les accords de partenariat économique (APE) avec l'UE. Destinée aux exportateurs, importateurs et opérateurs économiques agréés souhaitant optimiser leurs coûts douaniers. Référence : IBIG-DOA-CEE.",
'objectifs'=>"Comprendre le fonctionnement du Tarif extérieur commun (TEC) CEDEAO\nUtiliser le Schéma de libéralisation des échanges (SLE) de la CEDEAO\nConnaître les avantages douaniers liés au statut d'OEA (Opérateur économique agréé)\nMaîtriser le régime des zones franches industrielles en Côte d'Ivoire\nUtiliser les APE UE-CEDEAO pour l'exportation vers l'Europe\nOptimiser les coûts douaniers grâce aux régimes préférentiels\nÉviter les infractions douanières liées aux régimes préférentiels",
'modules'=>"M1 — TEC CEDEAO (3h) : structure, bandes tarifaires, mesures de sauvegarde, liste de concessions\nM2 — SLE CEDEAO (3h) : conditions d'origine, certificat de circulation A.ISK, procédures\nM3 — OEA en Côte d'Ivoire (3h) : critères d'agrément, avantages, procédure de demande\nM4 — Zones franches industrielles (4h) : ZFI CI, avantages fiscaux et douaniers, conditions d'éligibilité\nM5 — APE UE-CEDEAO (4h) : contenu de l'accord, produits couverts, règles d'origine, utilisation pratique\nM6 — Optimisation douanière et risques (3h) : arbitrage entre régimes, red flags, contrôles douaniers"],

['slug'=>'declaration-douane-sydonia-pratique','titre'=>'Déclaration en douane et utilisation pratique de SYDONIA','domaine'=>'Douanes & Commerce international','duree'=>'15H','tarif_en_ligne'=>170000,'tarif_presentiel'=>215000,
'description'=>"Formation pratique de 15 heures entièrement dédiée à la saisie et au traitement des déclarations en douane sur le système SYDONIA World utilisé en Côte d'Ivoire. Destinée aux déclarants en douane, transitaires et agents de dédouanement. Exercices sur des cas réels d'importation et d'exportation. Référence : IBIG-DOA-SYD.",
'objectifs'=>"Naviguer dans l'interface SYDONIA World et créer un compte opérateur\nSaisir une déclaration import et export complète\nJoindre les documents requis et valider la déclaration\nEffectuer le paiement en ligne des droits et taxes\nSuivre le circuit de dédouanement jusqu'à la mainlevée\nGérer les erreurs et les rejets de déclaration\nÉditer les états et les certificats de dédouanement",
'modules'=>"M1 — Présentation de SYDONIA World (2h) : fonctionnalités, accès, profils utilisateurs, modules\nM2 — Saisie d'une déclaration import (5h) : entête, lignes articles, valeur, régime, documents joints, validation\nM3 — Saisie d'une déclaration export (3h) : spécificités export, certificat d'exportation, statistiques\nM4 — Paiement et mainlevée (2h) : modes de paiement, quittance, bon à enlever\nM5 — Gestion des rejets et des corrections (2h) : causes de rejet, procédure de correction, recours\nM6 — Exercices pratiques supervisés (1h) : 2 dossiers complets de bout en bout"],

['slug'=>'pratique-import-export-commande-paiement','titre'=>'Pratique du commerce import-export : de la commande au paiement','domaine'=>'Douanes & Commerce international','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur la pratique opérationnelle du commerce international. Couvre le cycle complet d'une opération d'importation ou d'exportation : prospection des fournisseurs/clients, offre commerciale, contrat, modes de paiement internationaux, logistique, dédouanement et règlement des litiges. Référence : IBIG-DOA-IMP.",
'objectifs'=>"Identifier des fournisseurs internationaux fiables et négocier un contrat\nRédiger et analyser un contrat de vente internationale\nChoisir le mode de paiement adapté (crédit documentaire, remise, virement)\nOrganiser la logistique d'une opération import-export\nGérer les risques de change et de non-paiement\nDédouaner des marchandises à l'import et à l'export\nRégler un litige commercial international",
'modules'=>"M1 — Prospection et sélection des partenaires (3h) : sources de fournisseurs/clients, due diligence, qualification\nM2 — Négociation et contrat international (4h) : clauses essentielles, CISG, choix du droit applicable, force majeure\nM3 — Modes de paiement internationaux (5h) : virement SWIFT, remise documentaire, crédit documentaire (STAND-BY, LC)\nM4 — Logistique et transport (4h) : Incoterms, choix du mode de transport, courtier, assurance\nM5 — Dédouanement pratique (5h) : déclaration import/export, valeur, droits, transit\nM6 — Gestion des risques et litiges (4h) : risque de change, assurance-crédit, arbitrage CCI"],

/* ═══════════════════════════════════════════════════════════
   6. COMMUNICATION & RELATIONS PUBLIQUES
═══════════════════════════════════════════════════════════ */
['slug'=>'relations-presse-medias-afrique-francophone','titre'=>'Relations presse et médias en Afrique francophone','domaine'=>'Communication & Relations publiques','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur les relations avec les médias en Afrique francophone : presse écrite, radio, télévision et médias en ligne. Couvre la rédaction des communiqués et dossiers de presse, l'organisation des conférences de presse, le media training et la gestion des demandes d'interview. Référence : IBIG-COM-PRS.",
'objectifs'=>"Comprendre le paysage médiatique en Côte d'Ivoire et en Afrique francophone\nRédiger un communiqué de presse efficace et un dossier de presse complet\nOrganiser une conférence de presse réussie\nÉtablir et entretenir des relations durables avec les journalistes\nFormuler des messages clés adaptés aux différents médias\nSe préparer à un interview journalistique (TV, radio, presse)\nGérer la presse en situation de crise",
'modules'=>"M1 — Paysage médiatique en Côte d'Ivoire (2h) : presse, radio, TV, médias en ligne, réseaux sociaux\nM2 — Rédaction du communiqué de presse (3h) : structure, accroche, corps, citation, boilerplate\nM3 — Le dossier de presse (3h) : contenu, présentation, version digitale, kit presse\nM4 — Organisation d'une conférence de presse (3h) : planification, invitations, salle, déroulement, suivi\nM5 — Media training (5h) : messages clés, questions difficiles, langage corporel, simulations filmées\nM6 — Relations durables avec les journalistes (2h) : fichier contacts, exclusives, off the record, éthique\nM7 — Presse en situation de crise (2h) : cellule de crise, porte-parole, séquencement des messages"],

['slug'=>'community-management-strategie-social-media','titre'=>'Community management avancé et stratégie social media','domaine'=>'Communication & Relations publiques','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures pour les community managers et responsables marketing digital qui souhaitent professionnaliser leur présence sur les réseaux sociaux. Couvre la stratégie de contenu, la gestion de communautés engagées, la publicité sociale, le reporting et la gestion de la e-réputation. Référence : IBIG-COM-SMM.",
'objectifs'=>"Élaborer une stratégie social media cohérente avec les objectifs business\nProduire des contenus engageants adaptés à chaque plateforme (Facebook, Instagram, LinkedIn, TikTok)\nGérer et animer une communauté en ligne\nMettre en place et optimiser des campagnes publicitaires sociales\nAnalyser les performances avec les outils natifs et Google Analytics\nProtéger et gérer la e-réputation de la marque\nTraiter les commentaires négatifs et les crises sur les réseaux",
'modules'=>"M1 — Stratégie social media (3h) : audit, personas, objectifs SMART, KPI, calendrier éditorial\nM2 — Production de contenu (4h) : texte, image (Canva), vidéo courte (CapCut), Reels, stories\nM3 — Gestion de communauté (3h) : modération, réponses, engagement, ambassadeurs\nM4 — Publicité sociale (4h) : Meta Ads, LinkedIn Ads, ciblage, créatifs, optimisation, budget\nM5 — Analytics et reporting (3h) : Facebook Insights, LinkedIn Analytics, Google Analytics, rapport mensuel\nM6 — E-réputation et gestion de crise (3h) : veille, Google Alerts, réponse aux avis négatifs, procédures"],

['slug'=>'redaction-professionnelle-rapports-notes','titre'=>'Rédaction professionnelle : rapports, notes et correspondances','domaine'=>'Communication & Relations publiques','duree'=>'15H','tarif_en_ligne'=>170000,'tarif_presentiel'=>215000,
'description'=>"Formation de 15 heures pour améliorer la qualité de ses écrits professionnels : notes de service, comptes rendus, rapports d'activité, lettres administratives et emails. Axée sur la clarté, la concision et l'efficacité de la communication écrite en contexte francophone. Référence : IBIG-COM-RED.",
'objectifs'=>"Structurer efficacement un document professionnel\nRédiger une note de service claire et percutante\nProduire un compte rendu de réunion complet et utile\nÉcrire un rapport d'activité ou d'audit convaincant\nRédiger une lettre administrative conforme aux normes\nOptimiser ses emails professionnels\nÉviter les fautes fréquentes de langue et de style",
'modules'=>"M1 — Principes de la rédaction professionnelle (2h30) : clarté, concision, structuration, registre\nM2 — La note de service et la circulaire (2h30) : forme, fond, ton, diffusion\nM3 — Le compte rendu et le procès-verbal (3h) : prise de notes, rédaction, validation, archivage\nM4 — Le rapport professionnel (4h) : plan, introduction, développement, conclusions, recommandations, annexes\nM5 — Correspondance et email professionnels (3h) : formules d'appel et de clôture, objet, relances, netiquette"],

['slug'=>'communication-crise-gestion-reputation','titre'=>'Communication de crise et gestion de la réputation','domaine'=>'Communication & Relations publiques','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur la communication en situation de crise et la gestion de la réputation de l'entreprise. Couvre la préparation d'un plan de communication de crise, la gestion des médias et des réseaux sociaux en crise, le rôle du porte-parole et la reconstruction de la réputation après l'événement. Référence : IBIG-COM-CRS.",
'objectifs'=>"Identifier les types de crises pouvant affecter une organisation\nPréparer un plan de communication de crise avant qu'une crise survienne\nCréer et activer une cellule de crise efficace\nFormater les messages de crise selon l'audience (clients, médias, régulateurs)\nFormer et entraîner un porte-parole à la communication en situation de crise\nGérer les réseaux sociaux et la désinformation en temps de crise\nMettre en place une stratégie de reconstruction de la réputation post-crise",
'modules'=>"M1 — Typologies et mécanismes des crises (2h) : crises produit, sociale, judiciaire, médiatique, cyber\nM2 — Plan de communication de crise (3h) : dark site, messages pré-rédigés, arbre décisionnel, contact list\nM3 — Cellule de crise (3h) : composition, rôles, activation, salle de crise, outillage\nM4 — Messages et audiences (3h) : message triangle, communiqués, Q&R, dark post\nM5 — Porte-parole et media training de crise (4h) : préparation, messages clés, simulations d'interview filmées\nM6 — Réseaux sociaux et désinformation (3h) : écoute en temps réel, réponse, démenti, signalement\nM7 — Post-crise et reconstruction (2h) : bilan, leçons apprises, plan de rebond réputationnel"],

['slug'=>'relations-publiques-evenementiel-corporate','titre'=>'Relations publiques et organisation d\'événements corporate','domaine'=>'Communication & Relations publiques','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur les relations publiques stratégiques et l'organisation d'événements d'entreprise en Afrique francophone. Couvre la stratégie RP, les relations institutionnelles, le lobbying éthique, l'organisation de séminaires, de lancements de produits et d'événements de networking. Référence : IBIG-COM-EVT.",
'objectifs'=>"Élaborer une stratégie de relations publiques alignée sur les objectifs de l'entreprise\nGérer les relations avec les parties prenantes institutionnelles (gouvernement, régulateurs)\nOrganiser un événement corporate de A à Z (conférence, séminaire, lancement)\nProduire des supports de communication institutionnelle de qualité\nMettre en place un programme de mécénat ou de RSE communicant\nMesurer le ROI des actions de relations publiques\nConstruire un réseau professionnel stratégique",
'modules'=>"M1 — Stratégie RP (3h) : cartographie des parties prenantes, objectifs, messages, plan d'action\nM2 — Relations institutionnelles et lobbying (3h) : relations gouvernementales, associations professionnelles, éthique\nM3 — Organisation d'événements (6h) : brief, cahier des charges, prestataires, logistique, animation, bilan\nM4 — Supports de communication institutionnelle (4h) : rapport annuel, brochure corporate, présentation institutionnelle\nM5 — Mécénat et RSE communicante (3h) : partenariats, communication de l'engagement, label RSE\nM6 — Mesure et ROI des RP (3h) : indicateurs de couverture médiatique, enquêtes de notoriété, bilan RP\nM7 — Networking stratégique (3h) : cercles professionnels, lobbying de réseau, personal branding dirigeant"],

/* ═══════════════════════════════════════════════════════════
   7. DROIT DES AFFAIRES OHADA
═══════════════════════════════════════════════════════════ */
['slug'=>'droit-ohada-affaires-pratique-entreprises','titre'=>'Droit OHADA des affaires : notions pratiques pour les entreprises','domaine'=>'Droit des affaires','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur le droit des affaires OHADA applicable aux entreprises de la zone. Couvre les actes uniformes essentiels : droit commercial général, sociétés commerciales, sûretés, recouvrement de créances, procédures collectives et arbitrage. Destinée aux dirigeants de PME, directeurs financiers, juristes d'entreprise et responsables administratifs. Référence : IBIG-DRT-OHD.",
'objectifs'=>"Comprendre l'organisation et les sources du droit OHADA\nMaîtriser les règles de base du droit commercial général (AUDCG)\nConnaître les formes de sociétés et les obligations des dirigeants (AUDSC)\nSécuriser les créances commerciales grâce aux sûretés (AUS)\nMettre en œuvre les procédures de recouvrement des créances (AUPSRVE)\nAnticiper les procédures collectives et protéger l'entreprise\nRecourir à l'arbitrage CCJA comme alternative au tribunal",
'modules'=>"M1 — Le droit OHADA : organisation et sources (3h) : Traité, actes uniformes, CCJA, ERSUMA\nM2 — Droit commercial général (4h) : fonds de commerce, RCCM, bail commercial, agent commercial\nM3 — Sociétés commerciales (5h) : SARL, SA, SAS, obligations des dirigeants, assemblées, dissolution\nM4 — Sûretés OHADA (4h) : cautionnement, nantissement, gage, hypothèque, rétention, fiducie\nM5 — Recouvrement et voies d'exécution (5h) : injonction de payer, saisies mobilières et immobilières\nM6 — Procédures collectives (2h) : conciliation, règlement préventif, redressement judiciaire, liquidation\nM7 — Arbitrage CCJA (2h) : clause compromissoire, procédure, sentence, exequatur"],

['slug'=>'contrats-commerciaux-redaction-ohada','titre'=>'Rédiger et sécuriser ses contrats commerciaux en droit OHADA','domaine'=>'Droit des affaires','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur la rédaction des contrats commerciaux dans le cadre du droit OHADA. Couvre les clauses essentielles, les pièges à éviter, les clauses de sauvegarde et la gestion des litiges contractuels. Nombreux modèles de contrats commentés et exercices de rédaction. Référence : IBIG-DRT-CTR.",
'objectifs'=>"Maîtriser les conditions de validité d'un contrat commercial en OHADA\nIdentifier et rédiger les clauses essentielles de chaque type de contrat\nInclure des clauses de sauvegarde efficaces (clause pénale, résolutoire, force majeure)\nChoisir le droit applicable et la juridiction compétente\nNégocier et réviser un contrat de prestation de services\nRédiger un contrat de distribution, d'agence ou de franchise\nGérer l'inexécution contractuelle et les litiges",
'modules'=>"M1 — Fondamentaux du droit des contrats OHADA (2h) : formation, conditions de validité, nullité\nM2 — Clauses essentielles et rédaction (4h) : objet, prix, délais, responsabilité, confidentialité, propriété intellectuelle\nM3 — Clauses de sauvegarde (3h) : clause pénale, résolutoire, limitation de responsabilité, force majeure\nM4 — Contrats de services et de prestation (4h) : contrat de prestation, SLA, conditions générales de vente\nM5 — Contrats de distribution et d'agence (4h) : distributeur, agent commercial, franchise, exclusivité\nM6 — Inexécution et litiges (3h) : mise en demeure, résolution, dommages-intérêts, médiation"],

['slug'=>'droit-travail-ivoirien-employeur','titre'=>'Droit du travail ivoirien : droits et obligations de l\'employeur','domaine'=>'Droit des affaires','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur le droit du travail ivoirien appliqué aux employeurs : embauche, contrats de travail, gestion des congés, discipline, licenciement et relations collectives. Nombreux cas pratiques tirés de la jurisprudence des prud'hommes d'Abidjan. Référence : IBIG-DRT-TRV.",
'objectifs'=>"Maîtriser les obligations légales de l'employeur en matière de droit du travail ivoirien\nRédiger les types de contrats de travail conformes au Code du travail\nGérer les congés, arrêts maladie, congés maternité et événements familiaux\nAppliquer les procédures disciplinaires légales\nProcéder à un licenciement (individuel ou économique) dans les règles\nGérer les relations avec les délégués du personnel et les syndicats\nÉviter les risques de requalification et de condamnation aux prud'hommes",
'modules'=>"M1 — Sources du droit du travail ivoirien (2h) : Code du travail, conventions collectives, règlement intérieur\nM2 — Contrats de travail (4h) : CDD, CDI, stage, sous-traitance, éléments essentiels, modification, requalification\nM3 — Gestion des absences et congés (3h) : congés payés, maladie, maternité, événements familiaux, calcul de l'indemnité\nM4 — Discipline et sanctions (3h) : pouvoir disciplinaire, faute simple/grave/lourde, procédure, délais\nM5 — Licenciement (4h) : cause réelle et sérieuse, procédure individuelle et économique, calcul des indemnités\nM6 — Relations collectives (4h) : délégués du personnel, droit syndical, grève, négociation collective"],

['slug'=>'recouvrement-voies-execution-ohada','titre'=>'Recouvrement de créances et voies d\'exécution OHADA','domaine'=>'Droit des affaires','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur les procédures de recouvrement de créances commerciales en droit OHADA. Couvre les procédures amiables et judiciaires, l'injonction de payer, les différentes saisies (saisie-attribution, saisie-vente, saisie immobilière) et la gestion du risque client. Référence : IBIG-DRT-REC.",
'objectifs'=>"Mettre en place un processus de relance amiable efficace\nChoisir et engager la procédure judiciaire de recouvrement appropriée\nObtenir et exécuter une injonction de payer OHADA\nProcéder à une saisie-attribution sur compte bancaire\nOrganiser une saisie-vente de biens meubles\nGérer une procédure de saisie immobilière\nEvaluer le risque client et sécuriser ses créances en amont",
'modules'=>"M1 — Gestion du risque client (2h) : notation client, garanties précontractuelles, assurance-crédit\nM2 — Relance amiable et mise en demeure (3h) : procédure de relance en 3 étapes, mise en demeure légale, négociation\nM3 — Injonction de payer OHADA (4h) : conditions, requête, ordonnance, opposition, force exécutoire\nM4 — Saisie-attribution (4h) : conditions, acte de saisie, déclaration du tiers, mainlevée, contestation\nM5 — Saisie-vente (4h) : commandement, inventaire, vente aux enchères, distribution du prix\nM6 — Saisie immobilière (3h) : commandement, audience éventuelle, adjudication, procédure simplifiée"],

['slug'=>'contentieux-commercial-arbitrage-ohada','titre'=>'Contentieux commercial et arbitrage en zone OHADA','domaine'=>'Droit des affaires','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur le règlement des litiges commerciaux en zone OHADA : médiation, arbitrage CCJA et arbitrage institutionnel national. Destinée aux juristes, dirigeants et conseils qui souhaitent comprendre et utiliser l'arbitrage comme alternative au tribunal étatique. Référence : IBIG-DRT-ARB.",
'objectifs'=>"Comprendre les mécanismes de résolution amiable des litiges commerciaux\nRédiger une clause compromissoire efficace dans un contrat\nEngager une procédure d'arbitrage devant la CCJA\nDéfendre les intérêts de son entreprise dans une procédure arbitrale\nConnaître les conditions de reconnaissance et d'exequatur d'une sentence arbitrale\nUtiliser les centres d'arbitrage nationaux (CACI, CAMC, etc.)\nÉvaluer le coût d'un arbitrage par rapport au recours judiciaire",
'modules'=>"M1 — Panorama des modes de résolution des litiges (2h) : médiation, conciliation, arbitrage, tribunal\nM2 — Fondements de l'arbitrage OHADA (4h) : Acte Uniforme d'Arbitrage, CCJA, arbitrage national vs international\nM3 — Clause compromissoire et compromis (4h) : rédaction, portée, arbitrabilité, pathologies de la clause\nM4 — Procédure arbitrale CCJA (6h) : demande, constitution du tribunal, échanges, audiences, délibéré\nM5 — Sentence arbitrale (4h) : rédaction, notification, voies de recours, recours en annulation\nM6 — Exequatur et exécution forcée (3h) : procédure d'exequatur, contestation, exécution dans un autre État OHADA\nM7 — Centres d'arbitrage nationaux (2h) : CACI CI, CAMC Cameroun, CATO Togo — procédures et coûts"],

/* ═══════════════════════════════════════════════════════════
   8. IMMOBILIER & URBANISME
═══════════════════════════════════════════════════════════ */
['slug'=>'promotion-immobiliere-monter-projet-ci','titre'=>'Promotion immobilière en Côte d\'Ivoire : monter un projet','domaine'=>'Immobilier & Urbanisme','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur le montage et la gestion d'une opération de promotion immobilière en Côte d'Ivoire. Couvre l'acquisition du foncier, le permis de construire, le financement bancaire, la commercialisation sur plan (VEFA) et la livraison. Destinée aux promoteurs, investisseurs et professionnels de l'immobilier. Référence : IBIG-IMM-PRO.",
'objectifs'=>"Identifier et sécuriser une opportunité foncière en Côte d'Ivoire\nMonter le programme architectural et technique d'une opération\nObtenir le permis de construire et les autorisations administratives\nFinancer un programme immobilier (fonds propres, crédit bancaire, préfinancements)\nCommercialiser un programme en VEFA (vente en l'état futur d'achèvement)\nSuivre et contrôler le chantier en tant que maître d'ouvrage\nGérer la livraison, les réserves et les garanties",
'modules'=>"M1 — Marché immobilier en Côte d'Ivoire (3h) : acteurs, tendances, segments résidentiel/commercial/logistique\nM2 — Acquisition du foncier (4h) : titre foncier, ACD, sécurisation juridique, due diligence foncière\nM3 — Programme et permis (4h) : brief architecte, CCTP, permis de construire, études techniques\nM4 — Montage financier (5h) : compte d'opération promoteur, financement bancaire, cash flow, seuil de rentabilité\nM5 — Commercialisation VEFA (4h) : contrat de réservation, acte VEFA notarié, plan de vente, marketing\nM6 — Suivi de chantier et livraison (5h) : contrôle de la qualité, réserves, PV de livraison, DOE, garanties"],

['slug'=>'gestion-locative-patrimoine-immobilier','titre'=>'Gestion locative et gestion de patrimoine immobilier','domaine'=>'Immobilier & Urbanisme','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur la gestion locative de biens immobiliers en Côte d'Ivoire : sélection des locataires, rédaction des baux, gestion des loyers, maintenance et optimisation de la rentabilité du patrimoine. Destinée aux propriétaires bailleurs, gestionnaires d'actifs et agents immobiliers. Référence : IBIG-IMM-LOC.",
'objectifs'=>"Sélectionner un locataire solvable et sécuriser l'entrée dans les lieux\nRédiger un contrat de bail conforme à la réglementation ivoirienne\nGérer les loyers, les charges et les révisions annuelles\nOrganiser la maintenance préventive et corrective des biens\nGérer les conflits avec les locataires et les procédures d'expulsion\nOptimiser la rentabilité de son patrimoine locatif\nConnaître la fiscalité applicable aux revenus locatifs en Côte d'Ivoire",
'modules'=>"M1 — Marché locatif en Côte d'Ivoire (2h) : prix, zones, types de biens, taux de vacance\nM2 — Sélection du locataire (2h) : critères, dossier, garanties, caution\nM3 — Contrat de bail (4h) : durée, loyer, charges, dépôt de garantie, état des lieux\nM4 — Gestion courante (4h) : quittances, révisions, charges de copropriété, sinistres\nM5 — Maintenance et travaux (3h) : entretien courant, travaux locataire/propriétaire, devis\nM6 — Conflits et expulsion (3h) : mise en demeure, conciliation, procédure judiciaire d'expulsion\nM7 — Fiscalité et optimisation (2h) : revenus fonciers, impôts, déductions, SCI"],

['slug'=>'droit-foncier-ivoirien-securiser-acquisitions','titre'=>'Droit foncier ivoirien : sécuriser ses acquisitions','domaine'=>'Immobilier & Urbanisme','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur le droit foncier en Côte d'Ivoire : statuts des terres, procédure d'immatriculation, titres fonciers, ACD, litiges fonciers et protection de l'acquéreur. Destinée aux investisseurs, entrepreneurs et particuliers souhaitant sécuriser leurs acquisitions immobilières. Référence : IBIG-IMM-FNC.",
'objectifs'=>"Comprendre le régime foncier ivoirien et les différents statuts de la terre\nDistinguer un titre foncier, un arrêté de concession définitive (ACD) et un certificat foncier\nSécuriser une acquisition foncière : due diligence, notaire, inscription au livre foncier\nIdentifier et éviter les arnaques foncières fréquentes en Côte d'Ivoire\nConnaître la procédure d'immatriculation d'un terrain\nGérer un litige foncier (recours administratif et judiciaire)\nComprendre le rôle du notaire dans les transactions immobilières",
'modules'=>"M1 — Régime foncier ivoirien (3h) : loi de 1998, domaine de l'État, terres coutumières, zones urbaines\nM2 — Types de droits fonciers (3h) : TF, ACD, certificat foncier, permis d'habiter, attestation villageoise\nM3 — Procédure d'immatriculation (4h) : demande, bornage, publication, délai, frais\nM4 — Due diligence foncière (4h) : vérification du titre, hypothèques, servitudes, recherches au livre foncier\nM5 — Fraudes et arnaques (3h) : ventes multiples, faux titres, vendeurs sans titre — comment se protéger\nM6 — Litiges fonciers (3h) : recours administratif, tribunal foncier, médiation coutumière"],

['slug'=>'evaluation-expertise-immobiliere','titre'=>'Évaluation et expertise immobilière','domaine'=>'Immobilier & Urbanisme','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur les méthodes d'évaluation des biens immobiliers en Côte d'Ivoire : méthode par comparaison, par le revenu, par le coût et discounted cash flow. Destinée aux agents immobiliers, banquiers, gestionnaires d'actifs et investisseurs qui ont besoin d'évaluer ou de challenger une valorisation immobilière. Référence : IBIG-IMM-EVA.",
'objectifs'=>"Comprendre les méthodes d'évaluation immobilière reconnues\nAppliquer la méthode par comparaison sur le marché ivoirien\nEvaluer un bien de rapport par la méthode du revenu\nCalculer la valeur d'un actif immobilier par la méthode DCF\nRédiger un rapport d'expertise immobilière\nChallengerun rapport d'évaluation bancaire\nComprendre la réglementation relative à l'expertise immobilière en CI",
'modules'=>"M1 — Le marché immobilier ivoirien et les acteurs de l'expertise (2h) : APIC, normes, déontologie\nM2 — Méthode par comparaison (4h) : sélection des références, ajustements, prix au m², application\nM3 — Méthode par le revenu (4h) : taux de capitalisation, revenu brut/net, application locaux commerciaux\nM4 — Méthode du coût (3h) : valeur de reconstruction, dépréciation physique et fonctionnelle\nM5 — Discounted Cash Flow (DCF) (4h) : projections de revenus, taux d'actualisation, valeur terminale\nM6 — Rapport d'expertise et déontologie (3h) : structure du rapport, limites, responsabilité de l'expert"],

['slug'=>'financement-immobilier-dossier-bancaire','titre'=>'Montage d\'un dossier de financement immobilier','domaine'=>'Immobilier & Urbanisme','duree'=>'15H','tarif_en_ligne'=>170000,'tarif_presentiel'=>215000,
'description'=>"Formation de 15 heures sur le montage d'un dossier de crédit immobilier auprès des banques ivoiriennes. Couvre les conditions d'octroi, les documents à fournir, le calcul de la capacité d'emprunt, la négociation des conditions de crédit et les garanties hypothécaires. Référence : IBIG-IMM-FIN.",
'objectifs'=>"Calculer sa capacité d'emprunt et son taux d'endettement\nConstituer un dossier de crédit immobilier complet et convaincant\nComparer les offres de crédit des banques ivoiriennes (taux, durée, frais)\nNégocier les conditions de crédit avec son banquier\nComprendre les mécanismes de garantie hypothécaire (hypothèque légale, CAHF)\nSuivre et gérer son crédit immobilier\nConnaître les aides et subventions au logement disponibles en Côte d'Ivoire",
'modules'=>"M1 — Capacité d'emprunt et taux d'endettement (2h30) : calcul, plafond légal, reste à vivre\nM2 — Dossier de crédit immobilier (3h) : pièces requises, fiche de renseignements, plan de financement\nM3 — Offres bancaires et comparaison (3h) : taux fixe/variable, durée, assurance emprunteur, frais de dossier\nM4 — Négociation avec la banque (2h30) : leviers de négociation, garanties alternatives\nM5 — Garanties hypothécaires (2h) : hypothèque légale, conventionnelle, CAHF, rang des créanciers\nM6 — Aides au logement et BHF (2h) : FHIMO, BHF, sociétés immobilières sociales"],

/* ═══════════════════════════════════════════════════════════
   9. TOURISME & HÔTELLERIE
═══════════════════════════════════════════════════════════ */
['slug'=>'gestion-etablissement-hotelier-afrique','titre'=>'Gestion d\'un établissement hôtelier en Afrique','domaine'=>'Tourisme & Hôtellerie','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur la gestion opérationnelle, financière et commerciale d'un hôtel, d'une résidence hôtelière ou d'un lodge en Afrique francophone. Couvre l'organisation des départements (réception, hébergement, restauration, technique), le yield management, la gestion des OTA et la relation client. Référence : IBIG-TOU-HOT.",
'objectifs'=>"Organiser les départements d'un établissement hôtelier\nMettre en place des procédures opérationnelles standard (SOP)\nOptimiser le taux d'occupation et le RevPAR\nGérer les relations avec les agences de voyage et les OTA (Booking, Expedia)\nPiloter les achats, les stocks et la restauration\nGérer et motiver le personnel hôtelier\nProduire les indicateurs de gestion hôtelière et un rapport mensuel",
'modules'=>"M1 — Organisation d'un établissement hôtelier (3h) : organigramme, départements, procédures, SOP\nM2 — Gestion de la réception et des réservations (4h) : check-in/check-out, PMS, overbooking, plaintes\nM3 — Hébergement et housekeeping (3h) : gestion des étages, normes de propreté, inventaire linge\nM4 — Restauration et bar (3h) : organisation F&B, menus, coût matière, contrôle de production\nM5 — Revenue management (4h) : taux d'occupation, ADR, RevPAR, tarification dynamique, OTA\nM6 — RH et formation du personnel (4h) : recrutement, standards de service, évaluation, planning\nM7 — Pilotage financier (4h) : budget hôtelier, ratios d'exploitation, rapport de gestion mensuel"],

['slug'=>'accueil-service-client-hotellerie-restauration','titre'=>'Accueil, service client et qualité en hôtellerie-restauration','domaine'=>'Tourisme & Hôtellerie','duree'=>'15H','tarif_en_ligne'=>170000,'tarif_presentiel'=>215000,
'description'=>"Formation de 15 heures sur les techniques d'accueil et de service client dans le secteur de l'hôtellerie et de la restauration. Couvre les standards de service, la communication avec les clients, la gestion des réclamations et la fidélisation. Destinée aux réceptionnistes, serveurs, responsables de salle et chefs de brigade. Référence : IBIG-TOU-ACC.",
'objectifs'=>"Maîtriser les techniques d'accueil et de prise en charge des clients\nCommuniquer efficacement avec des clients de cultures différentes\nAppliquer les standards de service propres au secteur hôtelier\nGérer les réclamations et transformer un client mécontent en client fidèle\nAssurer un service en salle de restaurant selon les normes de l'établissement\nVendre et up-seller les services de l'hôtel\nGarantir la satisfaction client et gérer les avis en ligne",
'modules'=>"M1 — Standards d'accueil et image de l'établissement (2h30) : présentation, langage, protocole, multiculturalisme\nM2 — Techniques de communication client (2h30) : écoute active, empathie, reformulation, gestion des silences\nM3 — Service en réception (3h) : check-in, check-out, conciergerie, information touristique, réservations\nM4 — Service en restauration (3h) : mise en place, prise de commande, service à la française/anglaise, débarrassage\nM5 — Gestion des réclamations (2h) : écoute, excuses, solution, compensation, suivi\nM6 — Fidélisation et avis en ligne (2h) : programme fidélité, réponse aux avis Booking/TripAdvisor/Google"],

['slug'=>'revenue-management-optimisation-revenus-hoteliers','titre'=>'Revenue management et optimisation des revenus hôteliers','domaine'=>'Tourisme & Hôtellerie','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur le revenue management appliqué à l'hôtellerie africaine. Apprendre à analyser la demande, à segmenter la clientèle, à définir une politique tarifaire dynamique et à optimiser la distribution en ligne pour maximiser le RevPAR. Référence : IBIG-TOU-REV.",
'objectifs'=>"Comprendre les fondamentaux du revenue management hôtelier\nAnalyser les indicateurs clés : taux d'occupation, ADR, RevPAR, GOPPAR\nSegmenter la clientèle et définir une tarification adaptée par segment\nMettre en place une politique de tarification dynamique\nOptimiser la distribution via les OTA (Booking.com, Expedia) et le canal direct\nGérer l'overbooking et les délogements\nProduire un rapport de revenue management mensuel",
'modules'=>"M1 — Fondamentaux du revenue management (2h) : histoire, définition, secteurs d'application, conditions d'efficacité\nM2 — Indicateurs clés (3h) : taux d'occupation, ADR, RevPAR, GOPPAR — calcul et interprétation\nM3 — Segmentation et yield (4h) : segmentation clientèle, prix par segment, calendrier tarifaire, restrictions\nM4 — Tarification dynamique (4h) : grille tarifaire, parité, BAR, offres packages, promotions\nM5 — Distribution en ligne (4h) : OTA vs direct, extranets Booking/Expedia, channel manager, GDS\nM6 — Rapport RM et outils (3h) : rapport hebdomadaire, forecast, outils RM (RMS, Excel)"],

['slug'=>'tourisme-digital-ota-reseaux-sociaux','titre'=>'Tourisme digital : OTA, réseaux sociaux et e-réputation','domaine'=>'Tourisme & Hôtellerie','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur le marketing digital appliqué au tourisme et à l'hôtellerie. Couvre la présence sur les OTA (Booking, Airbnb, Expedia), la stratégie réseaux sociaux, le SEO local, la gestion de la e-réputation et la mise en place d'un site de réservation en direct. Référence : IBIG-TOU-DIG.",
'objectifs'=>"Optimiser la fiche de son établissement sur Booking.com, Expedia et TripAdvisor\nMettre en place une stratégie de vente directe (site web + moteur de réservation)\nAnimer les réseaux sociaux d'un établissement touristique\nOptimiser son référencement local (Google My Business)\nGérer sa e-réputation et répondre aux avis en ligne\nUtiliser les données des OTA pour améliorer sa stratégie\nMettre en place des campagnes Google Ads pour un hôtel ou lodge",
'modules'=>"M1 — Écosystème digital touristique (2h) : acteurs, OTA, GDS, comparateurs, sites de réservation directe\nM2 — Optimisation sur les OTA (4h) : Booking.com, Expedia, TripAdvisor — fiche, photos, tarifs, promotions\nM3 — Vente directe (3h) : site web hôtelier, moteur de réservation (Cloudbeds, Beds24), avantages\nM4 — Réseaux sociaux hôteliers (3h) : Facebook, Instagram — contenu, stories, campagnes sponsored\nM5 — SEO local et Google My Business (3h) : fiche établissement, photos, avis, positions locales\nM6 — E-réputation (3h) : veille, réponses aux avis, stratégie de collecte d'avis positifs\nM7 — Google Ads pour l'hôtellerie (2h) : campagnes hôtel, Google Hotel Ads, budget"],

['slug'=>'normes-classement-hotelier-reglementation-ci','titre'=>'Normes de classement hôtelier et réglementation touristique en Côte d\'Ivoire','domaine'=>'Tourisme & Hôtellerie','duree'=>'15H','tarif_en_ligne'=>170000,'tarif_presentiel'=>215000,
'description'=>"Formation de 15 heures sur la réglementation touristique en Côte d'Ivoire, les normes de classement des établissements hôteliers (étoiles) et les obligations légales des opérateurs touristiques. Destinée aux directeurs d'hôtels, propriétaires d'établissements et responsables qualité. Référence : IBIG-TOU-NRM.",
'objectifs'=>"Connaître le cadre légal du tourisme en Côte d'Ivoire\nComprendre le système de classement hôtelier ivoirien (étoiles)\nConstituer un dossier de demande de classement\nMettre en conformité son établissement avec les normes requises\nConnaître les obligations fiscales et sociales des établissements touristiques\nPréparer une inspection du Ministère du Tourisme\nConnaître les aides et financements disponibles pour les établissements touristiques",
'modules'=>"M1 — Cadre légal du tourisme en Côte d'Ivoire (3h) : Ministère du Tourisme, OIT, lois et décrets, ONAT\nM2 — Classement hôtelier (4h) : critères de classement 1 à 5 étoiles, grille de notation, auto-évaluation\nM3 — Dossier de classement (3h) : pièces requises, procédure de dépôt, délais, renouvellement\nM4 — Mise en conformité (3h) : travaux requis, équipements, hygiène, sécurité incendie\nM5 — Fiscalité et obligations (2h) : taxe de séjour, TVA hôtelière, licences, obligations sociales"],

/* ═══════════════════════════════════════════════════════════
   10. ÉNERGIE & ENVIRONNEMENT
═══════════════════════════════════════════════════════════ */
['slug'=>'energies-renouvelables-solaire-afrique','titre'=>'Énergies renouvelables et solaire en Afrique : opportunités et installation','domaine'=>'Énergie & Environnement','duree'=>'25H','tarif_en_ligne'=>280000,'tarif_presentiel'=>355000,
'description'=>"Formation de 25 heures sur les énergies renouvelables en Afrique, avec un focus sur l'énergie solaire photovoltaïque. Couvre les opportunités d'investissement, la conception et le dimensionnement de systèmes solaires (résidentiel, commercial, mini-réseaux), les cadres réglementaires et les modèles de financement. Référence : IBIG-ENE-SOL.",
'objectifs'=>"Comprendre le potentiel des énergies renouvelables en Afrique de l'Ouest\nDimensionner un système solaire photovoltaïque résidentiel ou commercial\nChoisir les composants d'une installation solaire (panneaux, batteries, onduleurs)\nEvaluer la rentabilité d'un projet solaire et les délais de retour sur investissement\nConnaître le cadre réglementaire des énergies renouvelables en Côte d'Ivoire\nIdentifier les mécanismes de financement disponibles (DESCO, leasing)\nDévelopper une activité commerciale dans les énergies renouvelables",
'modules'=>"M1 — Panorama des énergies renouvelables en Afrique (3h) : solaire, éolien, hydraulique, biomasse — potentiel et enjeux\nM2 — Technologie photovoltaïque (4h) : fonctionnement, types de panneaux, courbe de performance, orientations\nM3 — Dimensionnement d'un système solaire (5h) : bilan énergétique, calcul de la puissance crête, stockage, onduleurs\nM4 — Rentabilité et financement (4h) : investissement, ROI, VAN, TRI, pay-back, crédit, DESCO\nM5 — Cadre réglementaire CI et sous-région (3h) : ANARE-CI, concessions, raccordement réseau, Net Metering\nM6 — Mini-réseaux ruraux (3h) : conception, gestion, business model, cas pratiques\nM7 — Créer une activité ER (3h) : SYSCEL, SOLARKIS, modèles de distribution, partenariats"],

['slug'=>'audit-energetique-entreprise-reduction-couts','titre'=>'Audit énergétique en entreprise et réduction des coûts','domaine'=>'Énergie & Environnement','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur la réalisation d'un audit énergétique en entreprise et la mise en place d'un plan d'action d'efficacité énergétique. Destinée aux directeurs techniques, responsables HSE, gestionnaires de patrimoine et consultants qui souhaitent réduire la facture énergétique de leur organisation. Référence : IBIG-ENE-AUD.",
'objectifs'=>"Comprendre les consommations énergétiques d'une entreprise industrielle ou tertiaire\nRéaliser un audit énergétique selon la méthodologie ISO 50001\nIdentifier les postes de gaspillage et les gisements d'économies\nPrioriser les actions correctives selon leur ROI\nRédiger un rapport d'audit énergétique professionnel\nMettre en place un système de management de l'énergie (SMénergie)\nSuivre les indicateurs de performance énergétique (IPE) et le tableau de bord",
'modules'=>"M1 — Bases de l'énergie en entreprise (2h) : électricité, groupe électrogène, climatisation, process industriel\nM2 — Méthodologie d'audit énergétique (3h) : ISO 50001, collecte des données, visite de site, mesures\nM3 — Analyse des consommations (4h) : comptage, diagramme de Pareto, identification des gaspillages\nM4 — Gisements d'économies (4h) : éclairage LED, climatisation, moteurs électriques, comportements\nM5 — Plan d'action et ROI (3h) : chiffrage des économies, priorisation, financement, plan d'action\nM6 — Rapport d'audit (2h) : structure, présentation, synthèse managériale\nM7 — Système de management de l'énergie (2h) : ISO 50001, IPE, tableau de bord, revue énergétique"],

['slug'=>'rse-conformite-environnementale-reporting','titre'=>'RSE, conformité environnementale et reporting développement durable','domaine'=>'Énergie & Environnement','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur la responsabilité sociétale des entreprises (RSE), la conformité aux réglementations environnementales et la rédaction d'un rapport de développement durable. Couvre les normes ISO 14001, la Global Reporting Initiative (GRI), le bilan carbone et les attentes des parties prenantes (investisseurs ESG, donneurs d'ordre). Référence : IBIG-ENE-RSE.",
'objectifs'=>"Comprendre les enjeux et les référentiels de la RSE (ISO 26000, GRI, ODD)\nRéaliser un diagnostic RSE de son organisation\nIdentifier les obligations légales environnementales applicables en Côte d'Ivoire\nMettre en place un système de management environnemental (ISO 14001)\nCalculer le bilan carbone de son organisation\nRédiger un rapport RSE/développement durable conforme aux standards GRI\nRépondre aux questionnaires ESG des donneurs d'ordre et investisseurs",
'modules'=>"M1 — RSE et développement durable : enjeux et référentiels (2h) : ISO 26000, ODD, GRI, CSRD européenne\nM2 — Diagnostic RSE (3h) : cartographie des parties prenantes, matrice de matérialité, évaluation des pratiques\nM3 — Réglementation environnementale CI (3h) : Code de l'environnement, ANDE, étude d'impact, normes\nM4 — ISO 14001 et SME (4h) : exigences de la norme, aspects environnementaux significatifs, plan d'action\nM5 — Bilan carbone (4h) : scopes 1/2/3, facteurs d'émission, calcul, pistes de réduction\nM6 — Rapport RSE/GRI (4h) : structure, indicateurs GRI, données quantitatives, vérification externe"],

['slug'=>'gestion-dechets-industriels-reglementation','titre'=>'Gestion des déchets industriels et réglementation environnementale','domaine'=>'Énergie & Environnement','duree'=>'15H','tarif_en_ligne'=>170000,'tarif_presentiel'=>215000,
'description'=>"Formation de 15 heures sur la gestion des déchets industriels et dangereux en Côte d'Ivoire. Couvre la classification des déchets, les obligations légales (loi sur l'environnement, Convention de Bâle), les filières de valorisation et d'élimination, et la prévention de la pollution. Destinée aux responsables HSE, ingénieurs et directeurs de site industriel. Référence : IBIG-ENE-DCH.",
'objectifs'=>"Classer les déchets selon leur nature et leur dangerosité\nConnaître les obligations légales de l'entreprise en matière de gestion des déchets\nIdentifier les filières de valorisation et d'élimination disponibles en Côte d'Ivoire\nRédiger un bordereau de suivi des déchets dangereux\nMettre en place un plan de gestion des déchets sur un site industriel\nPrévenir les déversements accidentels et gérer les incidents environnementaux\nCommuniquer sur la gestion des déchets dans le rapport RSE",
'modules'=>"M1 — Classification des déchets (2h30) : inertes, non dangereux, dangereux, DEEE, déchets hospitaliers\nM2 — Réglementation ivoirienne et internationale (3h) : Code de l'environnement CI, ANDE, Convention de Bâle\nM3 — Filières de valorisation et d'élimination (3h) : recyclage, incinération, décharge contrôlée, prestataires agréés\nM4 — Plan de gestion des déchets (3h) : diagnostic, tri à la source, stockage, transport, contrats\nM5 — Incidents environnementaux (2h) : déversement accidentel, plan d'urgence, déclaration à l'ANDE\nM6 — Reporting et communication (1h30) : bordereau de suivi, indicateurs, rapport RSE"],

['slug'=>'efficacite-energetique-batiment-construction','titre'=>'Efficacité énergétique dans le bâtiment et la construction','domaine'=>'Énergie & Environnement','duree'=>'20H','tarif_en_ligne'=>225000,'tarif_presentiel'=>285000,
'description'=>"Formation de 20 heures sur l'efficacité énergétique dans la conception et la rénovation des bâtiments en Afrique tropicale. Couvre l'architecture bioclimatique, l'isolation thermique, les systèmes de climatisation efficaces, l'éclairage LED et les certifications de bâtiment vert (HQE, EDGE). Destinée aux architectes, ingénieurs BTP, promoteurs et gestionnaires d'actifs. Référence : IBIG-ENE-BAT.",
'objectifs'=>"Comprendre les spécificités du confort thermique en Afrique tropicale\nApliquer les principes de l'architecture bioclimatique dans un projet\nChoisir les matériaux et systèmes d'isolation adaptés au climat ivoirien\nDimensionner un système de climatisation efficace\nConcevoir un éclairage LED performant et économique\nCalculer le bilan thermique d'un bâtiment\nConnaître les certifications de bâtiment vert disponibles (HQE, EDGE, LEED)",
'modules'=>"M1 — Climat tropical et confort thermique (2h) : rayonnement, humidité, vent — paramètres bioclimatiques\nM2 — Architecture bioclimatique (3h) : orientation, débords de toit, ventilation naturelle, végétalisation\nM3 — Isolation thermique (3h) : matériaux (laine de roche, polystyrène, enduits), toitures, parois, menuiseries\nM4 — Climatisation efficace (4h) : COP, EER, VRV/VRF, programmation, entretien, dimensionnement\nM5 — Éclairage LED et GTB (3h) : technologie LED, capteurs de présence, gestion technique du bâtiment\nM6 — Bilan thermique (3h) : calcul simplifié, logiciels (EnergyPlus, DesignBuilder), comparaison scénarios\nM7 — Certifications vertes (2h) : HQE, EDGE, LEED — critères, processus, avantages commerciaux"],

];

// ─── VÉRIFICATION SLUGS ───────────────────────────────────────────────────────
$slugs   = array_column($formations, 'slug');
$placeholders = implode(',', array_fill(0, count($slugs), '?'));
$chk = $pdo->prepare("SELECT slug FROM formations WHERE slug IN ($placeholders)");
$chk->execute($slugs);
$existing_slugs = array_flip($chk->fetchAll(PDO::FETCH_COLUMN));

// ─── PREVIEW ──────────────────────────────────────────────────────────────────
if ($confirm !== 'oui') {
    $libre = 0; $present = 0;
    foreach ($formations as $f) { isset($existing_slugs[$f['slug']]) ? $present++ : $libre++; }

    echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Preview — 10 nouveaux domaines</title>
    <style>body{font-family:monospace;background:#0d1f3c;color:#e2e8f0;padding:24px;font-size:13px}
    h1{color:#f59e0b}h2{color:#93c5fd}.ok{color:#34d399}.skip{color:#f87171}
    table{border-collapse:collapse;width:100%;margin-bottom:20px}
    th{background:#1e3a6e;color:#fff;padding:6px 10px;text-align:left}
    td{padding:5px 10px;border-bottom:1px solid #1e3a6e;vertical-align:top}
    .btn{display:inline-block;padding:12px 28px;background:#f59e0b;color:#000;border-radius:6px;text-decoration:none;font-weight:bold;margin:16px 0}
    </style></head><body>';
    echo '<h1>📋 Preview — 10 nouveaux domaines (' . count($formations) . ' formations)</h1>';
    echo '<p class="ok">✓ À insérer : <strong>' . $libre . '</strong></p>';
    echo '<p class="skip">⚠️ Déjà présentes (ignorées) : <strong>' . $present . '</strong></p>';

    echo '<table><thead><tr><th>#</th><th>Domaine</th><th>Titre</th><th>Durée</th><th>En ligne</th><th>Statut</th></tr></thead><tbody>';
    foreach ($formations as $i => $f) {
        $exists = isset($existing_slugs[$f['slug']]);
        $cls = $exists ? ' class="skip"' : '';
        echo '<tr' . $cls . '><td>' . ($i+1) . '</td><td>' . htmlspecialchars($f['domaine']) . '</td>'
            . '<td>' . htmlspecialchars($f['titre']) . '</td>'
            . '<td>' . $f['duree'] . '</td>'
            . '<td>' . number_format($f['tarif_en_ligne'],0,',',' ') . ' F</td>'
            . '<td>' . ($exists ? '⚠️ Ignoré' : '✓ Prêt') . '</td></tr>';
    }
    echo '</tbody></table>';
    echo '<a class="btn" href="?confirm=oui">🚀 CONFIRMER ET INSÉRER EN BASE</a>';
    echo '</body></html>';
    exit;
}

// ─── INSERTION ────────────────────────────────────────────────────────────────
$inseres = 0; $ignores = 0; $erreurs = [];

$stmt = $pdo->prepare("
    INSERT INTO formations (
        titre, slug, domaine, type_certificat,
        description, objectifs, modules, duree,
        mode, tarif_presentiel, tarif_en_ligne, tarif_hybride,
        frais_inscription, paiement_lien,
        date_debut, date_fin, mois, annee, session_label,
        statut, created_at, updated_at
    ) VALUES (
        ?, ?, ?, 'Certificat professionnel',
        ?, ?, ?, ?,
        'hybride', ?, ?, 0,
        0, '',
        '0000-00-00', '0000-00-00', '', 0, '',
        'active', NOW(), NOW()
    )
");

$stmt_niv = $pdo->prepare("
    INSERT INTO formation_niveaux (
        formation_id, niveau, duree_heures,
        tarif_en_ligne, tarif_presentiel, tarif_hybride,
        statut, ordre_affichage
    ) VALUES (?, 'intermediaire', ?, ?, ?, 0, 'actif', 2)
");

foreach ($formations as $f) {
    if (isset($existing_slugs[$f['slug']])) { $ignores++; continue; }

    $pdo->beginTransaction();
    try {
        $stmt->execute([
            $f['titre'], $f['slug'], $f['domaine'],
            $f['description'], $f['objectifs'], $f['modules'], $f['duree'],
            $f['tarif_presentiel'], $f['tarif_en_ligne'],
        ]);
        $fid = (int)$pdo->lastInsertId();
        $stmt_niv->execute([$fid, (int)$f['duree'], $f['tarif_en_ligne'], $f['tarif_presentiel']]);
        $pdo->commit();
        $inseres++;
    } catch (Throwable $e) {
        $pdo->rollBack();
        $erreurs[] = $f['slug'] . ' : ' . $e->getMessage();
    }
}

echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>OK — 10 domaines</title>
<style>body{font-family:monospace;background:#0d1f3c;color:#e2e8f0;padding:24px}
h1{color:#34d399}.ok{color:#34d399}.err{color:#f87171}a{color:#f59e0b;margin-right:16px}
ul{margin:0;padding:0 0 0 16px}</style></head><body>';
echo '<h1>✅ Insertion terminée</h1>';
echo '<p class="ok">✓ Formations insérées : <strong>' . $inseres . '</strong></p>';
echo '<p>⚠️ Ignorées (déjà présentes) : ' . $ignores . '</p>';
if ($erreurs) {
    echo '<p class="err">❌ Erreurs (' . count($erreurs) . ') :</p><ul>';
    foreach ($erreurs as $e) echo '<li>' . htmlspecialchars($e) . '</li>';
    echo '</ul>';
}
echo '<p><a href="../catalogue-formations.php">→ Voir le catalogue</a></p>';
echo '</body></html>';
